Repository Shopify/blockchain-components, pull requests merged in 2023-03, with the labels that each got.

#41 :green_heart: Fix CI by adding test scripts to shared package
  packages/shared/package.json
Labels: Type: Bug 🐛, SEV-4, 🤖Skip Changelog, Area: Testing 🧪

#37 :package: Patch Redux + use RTK alpha for full ESM support
  .changeset/eleven-pugs-hammer.md
  package.json
  packages/connect-wallet/package.json
  packages/connect-wallet/src/middleware/onConnectMiddleware.ts
  packages/connect-wallet/src/slices/walletSlice/walletSlice.ts
  patches/redux+5.0.0-alpha.2.patch
  yarn.lock
Labels: Type: Bug 🐛, Package: connect-wallet

#47 ➖ Removes redux-logger and makes use of custom logger middleware
  .changeset/proud-mangos-heal.md
  packages/connect-wallet/package.json
  packages/connect-wallet/src/middleware/loggerMiddleware.test.ts
  packages/connect-wallet/src/middleware/loggerMiddleware.ts
  packages/connect-wallet/src/store/configureStore.ts
  packages/connect-wallet/src/test/configureStore.ts
  yarn.lock
Labels: Type: Bug 🐛, SEV-3, Dependencies, Area: Testing 🧪

#40 [playground] Add AnalyticsListener
  apps/playground/src/components/AnalyticsListener.tsx
  apps/playground/src/index.tsx
Labels: 🤖Skip Changelog

#43 [analytics] Add `ClientAnalytics` tests
  packages/shared/src/utils/analytics/ClientAnalytics.test.ts
Labels: 🤖Skip Changelog

#27 :sparkles: Upgrades Storybook to v7 alpha version
  .github/workflows/chromatic.yml
  .storybook/decorators/withThemeProvider.tsx
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  packages/connect-wallet/package.json
  packages/connect-wallet/src/components/Playground/Playground.stories.tsx
  packages/shared/package.json
  packages/shared/src/components/Button/Button.stories.tsx
  packages/tokengate/package.json
  packages/tokengate/src/components/Tokengate/stories/discount/LockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/discount/UnlockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/exclusive/LockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/exclusive/UnlockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/playground/playground.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/template.tsx
  yarn.lock
Labels: 🤖Skip Changelog, Area: Tooling ⚒️

#50 [analytics] Add onClick tracking to shared Button component
  packages/shared/package.json
  packages/shared/src/components/Button/Button.test.tsx
  packages/shared/src/components/Button/Button.tsx
  packages/shared/src/components/Button/fixtures.ts
  packages/shared/src/components/Button/types.ts
  packages/shared/src/tests/helpers/ClientAnalytics.tsx
  packages/shared/src/tests/utils.ts
  packages/shared/src/utils/analytics/ClientAnalytics.test.ts
  packages/shared/src/utils/analytics/ClientAnalytics.ts
Labels: 🤖Skip Changelog

#54 :fire: Removes disabled story arguments
  packages/tokengate/src/components/Tokengate/stories/discount/LockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/discount/UnlockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/exclusive/LockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/exclusive/UnlockedTokengate.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/template.tsx
Labels: 🤖Skip Changelog, Package: tokengate, Type: Enhancement 📈

#52 [analytics] Add subscribe to all
  packages/shared/src/utils/analytics/ClientAnalytics.test.ts
  packages/shared/src/utils/analytics/ClientAnalytics.ts
Labels: 🤖Skip Changelog

#58 :memo: Initializes examples directory with Vite
  .gitignore
  README.md
  examples/README.md
  examples/vite/index.html
  examples/vite/package.json
  examples/vite/public/vite.svg
  examples/vite/src/App.css
  examples/vite/src/App.tsx
  examples/vite/src/assets/react.svg
  examples/vite/src/connect-wallet-config.ts
  examples/vite/src/index.css
  examples/vite/src/main.tsx
  examples/vite/src/vite-env.d.ts
  examples/vite/tsconfig.json
  examples/vite/vite.config.ts
  images/shopify-dark.svg
  images/shopify-light.svg
Labels: Area: Documentation 📝, 🤖Skip Changelog, Type: Enhancement 📈

#72 :package: Remove internal packages from dependencies list
  .changeset/fifty-carrots-taste.md
  packages/connect-wallet/package.json
  packages/connect-wallet/tsconfig.json
  packages/gate-context-client/package.json
  packages/gate-context-client/tsconfig.json
  packages/tokengate/package.json
  packages/tokengate/tsconfig.json
Labels: Type: Enhancement 📈

#63 [analytics] export functions instead of objects
  apps/playground/src/components/AnalyticsListener.tsx
  packages/blockchain-components/src/tests/helpers/ClientAnalytics.tsx
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/index.ts
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.test.ts
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.ts
  packages/shared/src/components/Button/Button.tsx
  packages/tokengate/src/components/Tokengate/Tokengate.tsx
Labels: 🤖Skip Changelog

#65 [analytics] Create new hook `useEventWithTracking`
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/index.ts
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.test.tsx
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.ts
  packages/shared/src/components/Button/Button.tsx
Labels: 🤖Skip Changelog

#81 :wrench: Configure TailwindCSS monorepo config
  package.json
  packages/connect-wallet/.prettierrc.cjs
  packages/connect-wallet/package.json
  packages/connect-wallet/postcss.config.cjs
  packages/connect-wallet/src/styles.css
  packages/connect-wallet/tailwind.config.cjs
  packages/shared/.prettierrc.cjs
  packages/shared/package.json
  packages/shared/postcss.config.cjs
  packages/shared/tailwind.config.cjs
  packages/tailwind-config/package.json
  packages/tailwind-config/tailwind.config.js
  packages/tokengate/.prettierrc.cjs
  packages/tokengate/package.json
  packages/tokengate/postcss.config.cjs
  packages/tokengate/src/styles.css
  packages/tokengate/tailwind.config.cjs
  yarn.lock
Labels: Area: Tooling ⚒️, Type: Enhancement 📈

#86 [Tailwind] shared/SkeletonThumbnail
  packages/shared/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx
  packages/tailwind-config/tailwind.config.js
  packages/tokengate/src/components/TokenBase/style.ts
Labels: Type: Enhancement 📈

#89 [Tailwind] shared/Spinner
  packages/shared/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx
  packages/shared/src/components/Spinner/Spinner.tsx
  packages/shared/src/components/Spinner/index.ts
  packages/shared/src/components/Spinner/style.ts
  packages/tailwind-config/tailwind.config.js
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#94 [Tailwind] tokengate/SoldOutButton
  packages/connect-wallet/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-wallet/src/components/ConnectButton/Popover.tsx
  packages/connect-wallet/src/styles.css
  packages/shared/src/components/Text/Text.tsx
  packages/tailwind-config/tailwind.config.js
  packages/tokengate/src/components/SoldOutButton/SoldOutButton.tsx
  packages/tokengate/src/components/SoldOutButton/style.ts
  packages/tokengate/src/styles.css
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#96 [Tailwind] tokengate/TokengateRequirementsBadge
  packages/tokengate/src/assets/icons/CrossBadge.tsx
  packages/tokengate/src/components/TokengateRequirements/TokengateRequirementsBadge.tsx
  packages/tokengate/src/components/TokengateRequirements/index.ts
  packages/tokengate/src/components/TokengateRequirements/utils.tsx
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#101 [Tailwind] tokengate/TokenListImage
  packages/tokengate/src/components/TokenList/TokenListImage.tsx
  packages/tokengate/src/components/TokenList/style.ts
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#103 [Tailwind] Remove styled components usage from `packages/tokengate`
  packages/tokengate/src/components/TokenList/index.ts
  packages/tokengate/src/components/Tokengate/stories/playground/playground.stories.tsx
  packages/tokengate/src/components/Tokengate/stories/playground/style.ts
  packages/tokengate/src/components/TokengateRequirements/index.ts
  packages/tokengate/styled.d.ts
  packages/tokengate/tsconfig.json
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#104 [Tailwind] connect-wallet/ConnectButton
  packages/connect-wallet/src/components/ConnectButton/ConnectButton.tsx
  packages/shared/src/components/Button/Button.tsx
  packages/shared/src/components/Button/index.ts
  packages/shared/src/index.ts
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#105 [Tailwind] connect-wallet/Popover
  packages/connect-wallet/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-wallet/src/components/ConnectButton/Popover.tsx
  packages/connect-wallet/src/components/ConnectButton/style.ts
  packages/connect-wallet/src/styles.css
  packages/tailwind-config/tailwind.config.js
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#107 [Tailwind] connect-wallet/ConnectorButton
  packages/connect-wallet/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-wallet/src/components/ConnectorButton/ConnectorButton.tsx
  packages/connect-wallet/src/components/ConnectorButton/style.ts
  packages/shared/src/components/Button/Button.tsx
  packages/shared/src/components/Button/types.ts
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#108 [Tailwind] connect-wallet/ConnectorIcon
  packages/connect-wallet/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-wallet/src/components/ConnectButton/Popover.tsx
  packages/connect-wallet/src/components/ConnectorButton/ConnectorButton.tsx
  packages/connect-wallet/src/components/ConnectorIcon/ConnectorIcon.tsx
  packages/connect-wallet/src/components/ConnectorIcon/style.ts
  packages/connect-wallet/src/components/GetAConnectorButton/GetAConnectorButton.tsx
  packages/connect-wallet/src/components/Modal/Screens/ConnectingScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/SignatureScreen.tsx
  packages/connect-wallet/src/components/QRCode/QRCode.tsx
  packages/connect-wallet/src/types/sizes.ts
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#114 [Tailwind] connect-wallet/GetAWalletScreen
  packages/connect-wallet/src/components/Modal/Screens/GetAWalletScreen.tsx
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#118 [Tailwind] connect-wallet/WhatAreWalletsScreen
  packages/connect-wallet/src/components/Modal/Screens/ConnectingScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/SignatureScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/WhatAreWalletsScreen.tsx
  packages/shared/src/icons/Asset.tsx
  packages/shared/src/icons/Gift.tsx
  packages/shared/src/icons/Key.tsx
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#119 [Tailwind] connect-wallet/Modal
  package.json
  packages/connect-wallet/src/components/Modal/Modal.tsx
  packages/connect-wallet/src/components/Modal/style.ts
  packages/tailwind-config/tailwind.config.js
  yarn.lock
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#120 [Tailwind] connect-wallet/QRCode + QRCodeSkeleton
  package.json
  packages/connect-wallet/src/components/QRCode/QRCode.tsx
  packages/connect-wallet/src/components/QRCode/QRCodeSkeleton.tsx
  packages/connect-wallet/src/components/QRCode/style.ts
  packages/tailwind-config/tailwind.config.js
  yarn.lock
Labels: 🤖Skip Changelog, Type: Enhancement 📈

#125 Create new `shopify` util folder in blockchain-components
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/const.ts
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.test.tsx
  packages/blockchain-components/src/utils/analytics/ClientAnalytics/utils.ts
  packages/blockchain-components/src/utils/shopify/const.ts
  packages/blockchain-components/src/utils/shopify/utils.test.ts
  packages/blockchain-components/src/utils/shopify/utils.ts
Labels: 🤖Skip Changelog

#127 [Tailwind] Updates examples to include stylesheets
  examples/README.md
  examples/cra/package.json
  examples/cra/src/index.tsx
  examples/nextjs/package.json
  examples/nextjs/pages/_app.tsx
  examples/vite/package.json
  examples/vite/src/main.tsx
Labels: Area: Documentation 📝, 🤖Skip Changelog

#130 Add wallet extensibility changes to CRA example app
  examples/cra/package.json
  examples/cra/src/connect-wallet-config.ts
  examples/cra/src/index.tsx
  packages/connect-wallet/src/types/connector.ts
Labels: 🤖Skip Changelog

#139 :bug: Adds polyfills to storybook
  .storybook/main.js
  apps/playground/vite.config.ts
  examples/vite-custom-theme/package.json
  examples/vite-custom-theme/vite.config.ts
  examples/vite/package.json
  examples/vite/vite.config.ts
  package.json
  yarn.lock
Labels: 🤖Skip Changelog, Area: Storybook 📖

#144 Refactor package READMEs to link to shopify.dev docs
  packages/connect-wallet/README.md
  packages/gate-context-client/README.md
  packages/tokengate/README.md
Labels: 🤖Skip Changelog

#152 🔨 Adds examples script to run examples more seamlessly
  .changeset/config.json
  .github/workflows/ci.yml
  README.md
  examples/README.md
  examples/cra/package.json
  examples/nextjs/package.json
  examples/remix/package.json
  examples/vite-custom-theme/package.json
  examples/vite/package.json
  package.json
  packages/blockchain-components/README.md
  packages/connect-wallet/README.md
  packages/gate-context-client/README.md
  packages/tokengate/README.md
  scripts/run-example.mjs
  yarn.lock
Labels: 🤖Skip Changelog, Area: Tooling ⚒️, Type: Enhancement 📈

#153 🐛 Addresses missing text colors in packages
  .changeset/thick-pianos-add.md
  packages/connect-wallet/src/components/GetAConnectorButton/GetAConnectorButton.tsx
  packages/connect-wallet/src/components/Modal/Modal.tsx
  packages/connect-wallet/src/components/Modal/Screens/ConnectingScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/DelegateWalletsScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/SignatureScreen.tsx
  packages/connect-wallet/src/components/Modal/Screens/WhatAreWalletsScreen.tsx
  packages/connect-wallet/src/components/VaultList/VaultList.tsx
  packages/tokengate/src/components/Card/Card.tsx
  packages/tokengate/src/components/TokenBase/TokenBase.tsx
  packages/tokengate/src/components/TokengateRequirements/TokengateRequirementsSeparator.tsx
Labels: Type: Bug 🐛, SEV-3, Package: connect-wallet, Package: tokengate
